Fix libvirt domain XML generation for tap driver
When tap:aio was selected, an empty element was used without being
closed, generating the following error:

UnexpectedError: Problem creating the VM: at line 20: Opening and ending tag mismatch: driver line 17 and disk